#!/bin/sh
set -e
BUILD_DIR=$(pwd)
PREFIX=${BUILD_DIR}"/usr/"

#check if compiler exists
clear

OE_PATH=/home/socma/versetc/boxmake/simple3/support/toolchains/arm_dream/bin
printf "Set Compiler Path... '"${OE_PATH}"'\n\n"
export PATH=$PATH:$OE_PATH

HOST=arm-newnigma2-linux-gnueabihf
GCC=${HOST}"-gcc"
GPP=${HOST}"-g++"
CC=${GCC}
CXX=${GPP}

CPPFLAGS="-mhard-float"

cd build

echo
echo "###############################################################"
echo "#                                                             #"
echo "#                        Build Hard-FPU		            #"
echo "#                                                             #"
echo "###############################################################"
echo ""
echo ""

sleep 1

echo "[Hardfloat] Clean directory..."
make clean -i

echo "[Hardfloat] Configure..."
./configure CC=${CC} CXX=${CXX} --host=${HOST} CPPFLAGS="${CPPFLAGS}" --prefix=${PREFIX}

echo "[Hardfloat] Make..."
make  -j2
make install

echo "[Hardfloat] >>>> Build Hard-FPU Finisched <<<<"

mv $PREFIX/bin/enigmalight $PREFIX/bin/enigmalight_oe20_hf

echo
echo
echo "###############################################################"
echo "#                                                             #"
echo "# 	                Build  Soft-FPU               	    #"
echo "#                                                             #"
echo "###############################################################"
echo ""
echo ""

sleep 1

CPPFLAGS="-msoft-float"

echo "[Softfloat] Clean directory..."
make clean -i

echo "[Softfloat] Configure..."
./configure CC=${CC} CXX=${CXX} --host=${HOST} CPPFLAGS="${CPPFLAGS}" --prefix=${PREFIX}

echo "[Softfloat] Make..."
make -j2
make install

echo "[Softfloat] >>>> Build Soft-FPU Finisched <<<<"

make clean -i -s

mv $PREFIX/bin/enigmalight $PREFIX/bin/enigmalight_oe20_sf

cd ..

printf "Build finisched!!\n"
printf "Files are found in build/usr/bin, SF means softfloat for dm800 etc.. and HF for the devices with FPU support\n"
printf "Exit.."

exit 0;
#!/bin/sh
set -e
BUILD_DIR=$(pwd)
PREFIX=${BUILD_DIR}"/usr/"

#check if compiler exists
clear

OE_PATH=/home/socma/versetc/boxmake/simple3/support/toolchains/arm_dream/bin
printf "Set Compiler Path... '"${OE_PATH}"'\n\n"
export PATH=$PATH:$OE_PATH

HOST=arm-newnigma2-linux-gnueabihf
GCC=${HOST}"-gcc"
GPP=${HOST}"-g++"
CC=${GCC}
CXX=${GPP}

CPPFLAGS="-mhard-float"

cd build

echo
echo "###############################################################"
echo "#                                                             #"
echo "#                        Build Hard-FPU		            #"
echo "#                                                             #"
echo "###############################################################"
echo ""
echo ""

sleep 1

echo "[Hardfloat] Clean directory..."
make clean -i

echo "[Hardfloat] Configure..."
./configure CC=${CC} CXX=${CXX} --host=${HOST} CPPFLAGS="${CPPFLAGS}" --prefix=${PREFIX}

echo "[Hardfloat] Make..."
make  -j2
make install

echo "[Hardfloat] >>>> Build Hard-FPU Finisched <<<<"

mv $PREFIX/bin/enigmalight $PREFIX/bin/enigmalight


exit 0;
